// Auto-generated by scripts/update-backgrounds.js
// Do not edit manually. Run 'node scripts/update-backgrounds.js' to update.

window.VIDEO_BACKGROUNDS = [
  {
    "filename": "aurora.mp4",
    "displayName": "Aurora"
  },
  {
    "filename": "sky.mp4",
    "displayName": "Sky"
  }
];
