CREATE TABLE IF NOT EXISTS coaching_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  pattern_name TEXT,
  bpm INTEGER,
  total_notes INTEGER,
  correct_notes INTEGER,
  note_accuracy INTEGER,
  timing_accuracy INTEGER,
  overall_score INTEGER,
  note_results JSONB,
  problem_measures JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE coaching_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own coaching sessions" 
ON coaching_sessions FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own coaching sessions" 
ON coaching_sessions FOR INSERT 
WITH CHECK (auth.uid() = user_id);
